server:
  port: 8086 #服务端口

spring:
  application:
    name: itcast-microservice-configserver #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: http://172.16.55.138:10080/zhangzhijun/itcast-config-server.git
          #username: zhangzhijun
          #password: 123456